import type { TimeSlot, Contact, ScheduleDay, Venue, AppState } from '../types/schedule';
import { timeToSlot, durationToSlots } from '../utils/time';

const SEED_DAYS: ScheduleDay[] = [
  { id: 'wed', label: 'Wed 5/27 — Load-In', date: '2025-05-27' },
  { id: 'thu', label: 'Thu 5/28 — Day 1', date: '2025-05-28' },
  { id: 'fri', label: 'Fri 5/29 — Day 2', date: '2025-05-29' },
];

const SEED_VENUES: Venue[] = [
  { id: 'main-stage', label: 'Main Stage' },
  { id: 'll-a', label: 'LL-A' },
  { id: 'll-b', label: 'LL-B' },
];

// === Contact IDs (stable so slot references work) ===
const C = {
  ehren:       'c-ehren-stanhope',
  chris:       'c-chris-loveless',
  joeGiroux:   'c-joe-giroux',
  ryan:        'c-ryan-kirlin',
  robArnott:   'c-rob-arnott',
  jeffChang:   'c-jeff-chang',
  danielBunn:  'c-daniel-bunn',
  josephAqr:   'c-joseph-liberman',
  alex:        'c-alex-fm',
  nuveen:      'c-nuveen-brooklyn',
  savina:      'c-savina-rizova',
  meb:         'c-meb-faber',
  paulB:       'c-paul-bouchey',
  andrewBeer:  'c-andrew-beer',
  daveNadig:   'c-dave-nadig',
  shangChou:   'c-shang-chou',
  keenan:      'c-keenan-szulik',
  jimCarroll:  'c-jim-carroll',
  terryCook:   'c-terry-cook',
  nickR:       'c-nick-rosenthal',
  robertD:     'c-robert-dupree',
  jimDubeck:   'c-jim-dubeck',
  johnWest:    'c-john-west',
  ralphD:      'c-ralph-drybrough',
  royHaya:     'c-roy-haya',
  thomasB:     'c-thomas-boczar',
  mikeAllison: 'c-mike-allison',
  rafaelZ:     'c-rafael-zayas',
  jonFT:       'c-jon-ft',
  daveReynolds:'c-dave-reynolds',
  michaelL:    'c-michael-liebeskind',
  mohsenG:     'c-mohsen-ghazi',
};

const SEED_CONTACTS: Contact[] = [
  // --- Canvas ---
  { id: C.ehren, name: 'Ehren Stanhope', email: 'ehren.stanhope@osam.com', phone: '', role: 'speaker', notes: 'Chief Investment Strategist, Canvas' },
  { id: C.chris, name: 'Chris Loveless', email: 'chris.loveless@osam.com', phone: '', role: 'speaker', notes: 'President, Canvas. Support: Laura Kelleher laura.kelleher@osam.com' },
  { id: C.joeGiroux, name: 'Joe Giroux', email: 'joe.giroux@osam.com', phone: '', role: 'speaker', notes: 'Portfolio Manager, Canvas' },

  // --- Speakers ---
  { id: C.ryan, name: 'Ryan Patrick Kirlin', email: 'ryan@alphaarchitect.com', phone: '', role: 'speaker', notes: 'President, Alpha Architect' },
  { id: C.robArnott, name: 'Rob Arnott', email: 'arnott@rallc.com', phone: '', role: 'speaker', notes: 'Founder & Chairman, Research Affiliates. Support: Brent Leadbetter leadbetter@rallc.com. Will send PPT closer to event.' },
  { id: C.jeffChang, name: 'Jeff Chang', email: 'jchang@vestfin.com', phone: '', role: 'speaker', notes: 'First Trust. Support: Brianna Fessler bfessler@vestfin.com' },
  { id: C.danielBunn, name: 'Daniel Bunn', email: 'dbunn@taxfoundation.org', phone: '', role: 'speaker', notes: 'President & CEO, Tax Foundation. VIP. Support: Katelynn Barbosa kbarbosa@taxfoundation.org' },
  { id: C.josephAqr, name: 'Joseph Liberman', email: 'Joseph.Liberman@aqr.com', phone: '', role: 'speaker', notes: 'Managing Director Quantitative Research, AQR. Support: Dan.Villalon@aqr.com' },
  { id: C.alex, name: 'Alex Morris', email: 'amorris@fminvest.com', phone: '', role: 'speaker', notes: 'f/m Investments. Support: Courtney Sheehy csheehy@fminvest.com' },
  { id: C.savina, name: 'Savina Rizova', email: 'Savina.Rizova@dimensional.com', phone: '', role: 'speaker', notes: 'Co-CIO, DFA. Support: Taylor.Smith@dimensional.com, Kacie.Walsh@dimensional.com' },
  { id: C.meb, name: 'Meb Faber', email: '', phone: '', role: 'speaker', notes: 'Cambria. Kai sent email requesting session title. 25 min Day 2.' },
  { id: C.paulB, name: 'Paul Bouchey', email: 'paul.bouchey@gmail.com', phone: '', role: 'speaker', notes: 'Managing Director Applied Research / Former CIO, Parametric (Morgan Stanley)' },
  { id: C.andrewBeer, name: 'Andrew Beer', email: 'a@dbi.co', phone: '', role: 'speaker', notes: 'Managing Member, DBi' },
  { id: C.jonFT, name: 'Jon', email: '', phone: '', role: 'speaker', notes: 'First Trust. Fri main panel.' },

  // --- Emcees ---
  { id: C.shangChou, name: 'Shang Chou', email: 'shang@dishmicap.com', phone: '', role: 'emcee', notes: 'Managing Partner, Dishmi. Emcee as needed both days.' },
  { id: C.daveNadig, name: 'Dave Nadig', email: 'dave@etf.com', phone: '', role: 'emcee', notes: 'President & Director of Research, ETF.com. Emcee as needed.' },

  // --- Panelists ---
  { id: C.keenan, name: 'Keenan Szulik', email: 'kszulik8@gmail.com', phone: '', role: 'panelist', notes: 'CEO, Slocum Management. Practitioner Group Host.' },
  { id: C.jimCarroll, name: 'Jim Carroll', email: 'jim.carroll@ballastrockpw.com', phone: '', role: 'panelist', notes: 'PPLI panel, Ballast Rock' },
  { id: C.terryCook, name: 'Terry Cook', email: 'terry@parcionpw.com', phone: '', role: 'panelist', notes: 'Co-CEO, Parcion. OZ Panel.' },
  { id: C.nickR, name: 'Nick Rosenthal', email: 'nrosenthal@griffincapital.com', phone: '', role: 'panelist', notes: 'Principal, Griffin Capital. OZ Panel. Support: Matt Cardall mcardall@cimgroup.com' },
  { id: C.robertD, name: 'Robert Dupree', email: 'rdupree@cimgroup.com', phone: '', role: 'panelist', notes: 'Co-Head of Infrastructure, CIM Group. OZ Panel.' },
  { id: C.jimDubeck, name: 'Jim Dubeck', email: 'jim.dubeck@mossadams.com', phone: '', role: 'panelist', notes: 'Moss Adams. OZ Panel.' },
  { id: C.johnWest, name: 'John West', email: '', phone: '', role: 'panelist', notes: 'RE/Arqitel. Thu breakout.' },
  { id: C.ralphD, name: 'Ralph Drybrough', email: 'rd@fortpointcap.com', phone: '', role: 'panelist', notes: 'Managing Partner, Fort Point Capital. Fri breakout practitioner group.' },
  { id: C.royHaya, name: 'Roy Haya', email: 'rh@fortpointcap.com', phone: '', role: 'panelist', notes: 'Head of Derivative Solutions, Fort Point Capital. Fri breakout practitioner group.' },
  { id: C.thomasB, name: 'Thomas Boczar', email: 'thomas.boczar@outlook.com', phone: '', role: 'panelist', notes: 'Consultant. Fri breakout practitioner group.' },
  { id: C.mikeAllison, name: 'Mike Allison', email: 'mike@investmentresearchpartners.com', phone: '', role: 'panelist', notes: 'Strategist & PM, IRP. Fri breakout practitioner group.' },

  // --- 351 Panel ---
  { id: C.rafaelZ, name: 'Rafael Zayas', email: '', phone: '', role: 'panelist', notes: '351 Panel' },

  // --- PPLI Panel ---
  { id: C.daveReynolds, name: 'Dave Reynolds', email: '', phone: '', role: 'panelist', notes: 'Spearhead (largest SMA platform for PPLI). PPLI Panel Moderator.' },
  { id: C.michaelL, name: 'Michael Liebeskind', email: '', phone: '', role: 'panelist', notes: 'Golconda. Power of the PPLI structure.' },
  { id: C.mohsenG, name: 'Mohsen Ghazi', email: '', phone: '', role: 'panelist', notes: 'Family office use cases for PPLI.' },
];

const SEED_SLOTS: TimeSlot[] = [
  // ===== WEDNESDAY — Load-In =====
  {
    id: 'wed-main-loadin',
    dayId: 'wed',
    venueId: 'main-stage',
    startSlot: timeToSlot(9, 0),
    durationSlots: durationToSlots(480),
    type: 'load-in',
    company: '',
    title: 'Load in (Fern & Staff)',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'wed-expo-loadin',
    dayId: 'wed',
    venueId: 'll-a',
    startSlot: timeToSlot(12, 0),
    durationSlots: durationToSlots(300),
    type: 'load-in',
    company: '',
    title: 'Load in (Expos)',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'wed-opening-hh',
    dayId: 'wed',
    venueId: 'main-stage',
    startSlot: timeToSlot(17, 0),
    durationSlots: durationToSlots(60),
    type: 'event',
    company: 'Canvas',
    title: 'Opening HH',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },

  // ===== THURSDAY — Day 1: Main Stage =====
  {
    id: 'thu-main-doors',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(7, 15),
    durationSlots: durationToSlots(15),
    type: 'event',
    company: '',
    title: 'Doors & Registration',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'thu-main-breakfast',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(7, 30),
    durationSlots: durationToSlots(60),
    type: 'event',
    company: '',
    title: 'Breakfast + Expo',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'thu-main-keynote1',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(8, 30),
    durationSlots: durationToSlots(25),
    type: 'keynote',
    company: 'Canvas',
    title: 'Taxable Wealth: From Core Strategies to Cutting Edge Solutions',
    speakerIds: [C.chris, C.ehren],
    isSponsored: true,
    isTbd: false,
    notes: 'First 5 min: Chris Loveless Welcome Remarks, then Ehren Stanhope keynote. If (25) = Agenda will reflect 30 min timing.',
  },
  {
    id: 'thu-main-arnott',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(9, 0),
    durationSlots: durationToSlots(25),
    type: 'solo',
    company: 'Research Affiliates',
    title: 'Index Solutions for Tax Alpha Portfolios',
    speakerIds: [C.robArnott],
    isSponsored: false,
    isTbd: false,
    notes: 'Will send PPT closer to event',
  },
  {
    id: 'thu-main-break1',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(9, 30),
    durationSlots: durationToSlots(15),
    type: 'break',
    company: '',
    title: 'BREAK',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'thu-main-ryan',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(9, 45),
    durationSlots: durationToSlots(25),
    type: 'solo',
    company: 'Alpha Architect',
    title: 'What is a Syndic?',
    speakerIds: [C.ryan],
    isSponsored: true,
    isTbd: false,
    notes: '351 exchanges are a hot topic',
  },
  {
    id: 'thu-main-jeff',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(10, 15),
    durationSlots: durationToSlots(40),
    type: 'solo',
    company: 'First Trust',
    title: '',
    speakerIds: [C.jeffChang],
    isSponsored: true,
    isTbd: true,
    notes: 'Session title TBD',
  },
  {
    id: 'thu-main-open1',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(11, 0),
    durationSlots: durationToSlots(30),
    type: 'open',
    company: '',
    title: 'OPEN',
    speakerIds: [],
    isSponsored: false,
    isTbd: true,
    notes: '',
  },
  {
    id: 'thu-main-lunch',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(11, 30),
    durationSlots: durationToSlots(105),
    type: 'event',
    company: '',
    title: 'Lunch / Expo',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '30 dedicated / 1.5 food available',
  },
  {
    id: 'thu-main-alex',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(13, 15),
    durationSlots: durationToSlots(25),
    type: 'solo',
    company: 'f/m Investments',
    title: '',
    speakerIds: [C.alex],
    isSponsored: true,
    isTbd: true,
    notes: 'Session title TBD',
  },
  {
    id: 'thu-main-bunn',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(13, 45),
    durationSlots: durationToSlots(25),
    type: 'solo',
    company: 'Tax Foundation',
    title: '',
    speakerIds: [C.danielBunn],
    isSponsored: false,
    isTbd: true,
    notes: 'VIP. Session title TBD.',
  },
  {
    id: 'thu-main-break2',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(14, 15),
    durationSlots: durationToSlots(15),
    type: 'break',
    company: '',
    title: 'BREAK',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'thu-main-aqr',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(14, 30),
    durationSlots: durationToSlots(25),
    type: 'solo',
    company: 'AQR',
    title: '',
    speakerIds: [C.josephAqr],
    isSponsored: false,
    isTbd: true,
    notes: 'Session title TBD',
  },
  {
    id: 'thu-main-aqr-fort',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(15, 0),
    durationSlots: durationToSlots(25),
    type: 'solo',
    company: 'AQR / Fort Point',
    title: '',
    speakerIds: [C.ralphD, C.royHaya],
    isSponsored: false,
    isTbd: true,
    notes: 'Ralph Drybrough & Roy Haya. Session title TBD.',
  },
  {
    id: 'thu-main-break3',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(15, 30),
    durationSlots: durationToSlots(15),
    type: 'break',
    company: '',
    title: 'BREAK',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'thu-main-nuveen',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(15, 45),
    durationSlots: durationToSlots(25),
    type: 'panel',
    company: 'Nuveen / Brooklyn',
    title: '',
    speakerIds: [],
    isSponsored: true,
    isTbd: true,
    notes: 'Panel members TBD',
  },
  {
    id: 'thu-main-alliance',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(16, 15),
    durationSlots: durationToSlots(25),
    type: 'solo',
    company: 'Alliance',
    title: '',
    speakerIds: [],
    isSponsored: false,
    isTbd: true,
    notes: 'Speaker TBD',
  },
  {
    id: 'thu-main-closing',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(16, 45),
    durationSlots: durationToSlots(45),
    type: 'event',
    company: 'First Trust',
    title: 'FT Closing + Thu Happy Hour',
    speakerIds: [],
    isSponsored: true,
    isTbd: false,
    notes: '',
  },

  // ===== THURSDAY — LL-A Breakout =====
  {
    id: 'thu-lla-pimco',
    dayId: 'thu',
    venueId: 'll-a',
    startSlot: timeToSlot(12, 0),
    durationSlots: durationToSlots(20),
    type: 'solo',
    company: 'PIMCO',
    title: '',
    speakerIds: [],
    isSponsored: false,
    isTbd: true,
    notes: 'PIMCO #1 — speaker TBD',
  },
  {
    id: 'thu-lla-351',
    dayId: 'thu',
    venueId: 'll-a',
    startSlot: timeToSlot(12, 30),
    durationSlots: durationToSlots(20),
    type: 'panel',
    company: '',
    title: '351 Panel',
    speakerIds: [C.johnWest, C.meb, C.ryan, C.rafaelZ],
    panelLeaderId: C.johnWest,
    isSponsored: true,
    isTbd: false,
    notes: 'Moderator: John West. Panelists: Meb Faber, Ryan Kirlin, Rafael Zayas, TBD someone from Scharf. Ask Dorothy Friedrich dorothy@scharfinvestments.com',
  },

  // ===== THURSDAY — LL-B Breakout =====
  {
    id: 'thu-llb-oz',
    dayId: 'thu',
    venueId: 'll-b',
    startSlot: timeToSlot(12, 0),
    durationSlots: durationToSlots(25),
    type: 'panel',
    company: 'OZ / Griffin Capital / CIM Group',
    title: '',
    speakerIds: [C.terryCook, C.nickR, C.robertD, C.jimDubeck],
    isSponsored: false,
    isTbd: true,
    notes: 'Nick said he\'ll let Terry decide the Session Title (4/1). Support: Matt Cardall mcardall@cimgroup.com',
  },
  {
    id: 'thu-llb-johnwest',
    dayId: 'thu',
    venueId: 'll-b',
    startSlot: timeToSlot(12, 30),
    durationSlots: durationToSlots(20),
    type: 'solo',
    company: 'RE/Arqitel',
    title: '',
    speakerIds: [C.johnWest],
    isSponsored: false,
    isTbd: true,
    notes: 'Session title TBD',
  },

  // ===== FRIDAY — Day 2: Main Stage =====
  {
    id: 'fri-main-doors',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(7, 15),
    durationSlots: durationToSlots(15),
    type: 'event',
    company: '',
    title: 'Doors & Registration',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'fri-main-breakfast',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(7, 30),
    durationSlots: durationToSlots(60),
    type: 'event',
    company: '',
    title: 'Breakfast + Expo',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'fri-main-panel8',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(8, 30),
    durationSlots: durationToSlots(25),
    type: 'keynote',
    company: 'Canvas',
    title: 'AMA: Canvas and Coffee and Everything Taxable Wealth In Between',
    speakerIds: [C.joeGiroux],
    isSponsored: true,
    isTbd: false,
    notes: '',
  },
  {
    id: 'fri-main-savina',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(9, 0),
    durationSlots: durationToSlots(25),
    type: 'solo',
    company: 'Dimensional Fund Advisors',
    title: 'Long-Only and Long-Short SMAs – The Dimensional Perspective',
    speakerIds: [C.savina],
    isSponsored: false,
    isTbd: false,
    notes: 'Support: Taylor.Smith@dimensional.com, Kacie.Walsh@dimensional.com',
  },
  {
    id: 'fri-main-savina-panel',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(9, 30),
    durationSlots: durationToSlots(15),
    type: 'panel',
    company: '',
    title: 'Panel w/ Savina',
    speakerIds: [C.savina],
    isSponsored: false,
    isTbd: true,
    notes: 'Panel details TBD',
  },
  {
    id: 'fri-main-break1',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(10, 0),
    durationSlots: durationToSlots(15),
    type: 'break',
    company: '',
    title: 'BREAK',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'fri-main-firsttrust',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(10, 15),
    durationSlots: durationToSlots(25),
    type: 'panel',
    company: 'First Trust',
    title: '',
    speakerIds: [C.jonFT],
    isSponsored: true,
    isTbd: true,
    notes: 'First Trust Panel — Christian + who else? TBD',
  },
  {
    id: 'fri-main-meb',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(10, 45),
    durationSlots: durationToSlots(25),
    type: 'solo',
    company: 'Cambria',
    title: '',
    speakerIds: [C.meb],
    isSponsored: true,
    isTbd: true,
    notes: 'Kai sent email requesting session title. Checking if Meb can be end of day.',
  },
  {
    id: 'fri-main-lunch',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(11, 30),
    durationSlots: durationToSlots(90),
    type: 'event',
    company: '',
    title: 'Lunch / Expo',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '20 min dedicated',
  },
  {
    id: 'fri-main-open-1250',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(12, 50),
    durationSlots: durationToSlots(40),
    type: 'open',
    company: '',
    title: 'OPEN',
    speakerIds: [],
    isSponsored: false,
    isTbd: true,
    notes: 'Longview (30) - TBD',
  },
  {
    id: 'fri-main-practitioner',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(13, 30),
    durationSlots: durationToSlots(45),
    type: 'panel',
    company: 'Slocum Management',
    title: 'Live from the Field: Tax Aware Long-Short Working Group',
    speakerIds: [C.keenan],
    panelLeaderId: C.keenan,
    isSponsored: false,
    isTbd: false,
    notes: 'Practitioner Group. Brent Long-Short host.',
  },
  {
    id: 'fri-main-paul-ms',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(14, 15),
    durationSlots: durationToSlots(30),
    type: 'solo',
    company: 'Parametric (Morgan Stanley)',
    title: '',
    speakerIds: [C.paulB],
    isSponsored: true,
    isTbd: true,
    notes: 'Session title TBD',
  },
  {
    id: 'fri-main-break2',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(14, 45),
    durationSlots: durationToSlots(15),
    type: 'break',
    company: '',
    title: 'BREAK',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'fri-main-beer',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(15, 0),
    durationSlots: durationToSlots(30),
    type: 'solo',
    company: 'DBi',
    title: '',
    speakerIds: [C.andrewBeer],
    isSponsored: false,
    isTbd: true,
    notes: 'Session title TBD',
  },
  {
    id: 'fri-main-nadig',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(15, 30),
    durationSlots: durationToSlots(30),
    type: 'solo',
    company: 'ETF.com',
    title: '',
    speakerIds: [C.daveNadig],
    isSponsored: false,
    isTbd: true,
    notes: 'Session title TBD',
  },
  {
    id: 'fri-main-break3',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(16, 0),
    durationSlots: durationToSlots(15),
    type: 'break',
    company: '',
    title: 'BREAK',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'fri-main-vise',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(16, 15),
    durationSlots: durationToSlots(25),
    type: 'solo',
    company: 'Vise',
    title: '',
    speakerIds: [],
    isSponsored: false,
    isTbd: true,
    notes: 'Runik TBD',
  },
  {
    id: 'fri-main-closing',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(16, 45),
    durationSlots: durationToSlots(15),
    type: 'event',
    company: '',
    title: 'Brent Closing',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'fri-main-mariners',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(17, 0),
    durationSlots: durationToSlots(60),
    type: 'event',
    company: '',
    title: 'Mariners!',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },

  // ===== FRIDAY — LL-A Breakout =====
  {
    id: 'fri-lla-wealth',
    dayId: 'fri',
    venueId: 'll-a',
    startSlot: timeToSlot(11, 50),
    durationSlots: durationToSlots(20),
    type: 'panel',
    company: '',
    title: 'Single Stock Panel',
    speakerIds: [C.shangChou, C.mikeAllison],
    panelLeaderId: C.shangChou,
    isSponsored: false,
    isTbd: false,
    notes: 'Shang Chou running panel. Mike Allison only confirmed panelist so far.',
  },
  {
    id: 'fri-lla-pimco',
    dayId: 'fri',
    venueId: 'll-a',
    startSlot: timeToSlot(12, 20),
    durationSlots: durationToSlots(20),
    type: 'solo',
    company: 'PIMCO',
    title: '',
    speakerIds: [],
    isSponsored: false,
    isTbd: true,
    notes: 'PIMCO #2 — speaker TBD',
  },
  {
    id: 'fri-lla-open1',
    dayId: 'fri',
    venueId: 'll-a',
    startSlot: timeToSlot(12, 50),
    durationSlots: durationToSlots(20),
    type: 'open',
    company: '',
    title: 'OPEN',
    speakerIds: [],
    isSponsored: false,
    isTbd: true,
    notes: '',
  },
  {
    id: 'fri-lla-open2',
    dayId: 'fri',
    venueId: 'll-a',
    startSlot: timeToSlot(13, 30),
    durationSlots: durationToSlots(40),
    type: 'open',
    company: '',
    title: 'OPEN',
    speakerIds: [],
    isSponsored: false,
    isTbd: true,
    notes: '',
  },

  // ===== FRIDAY — LL-B Breakout =====
  {
    id: 'fri-llb-ppli',
    dayId: 'fri',
    venueId: 'll-b',
    startSlot: timeToSlot(11, 50),
    durationSlots: durationToSlots(20),
    type: 'panel',
    company: 'PPLI',
    title: '',
    speakerIds: [C.daveReynolds, C.michaelL, C.jimCarroll, C.mohsenG],
    panelLeaderId: C.daveReynolds,
    isSponsored: false,
    isTbd: true,
    notes: 'Moderator: Dave Reynolds (Spearhead). Michael Liebeskind (Golconda) — power of PPLI structure. Jim Carroll — investment flexibility of SMAs for PPLI. Mohsen Ghazi — family office use cases.',
  },
  {
    id: 'fri-llb-open1',
    dayId: 'fri',
    venueId: 'll-b',
    startSlot: timeToSlot(12, 20),
    durationSlots: durationToSlots(20),
    type: 'open',
    company: '',
    title: 'OPEN',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'fri-llb-open2',
    dayId: 'fri',
    venueId: 'll-b',
    startSlot: timeToSlot(12, 50),
    durationSlots: durationToSlots(20),
    type: 'open',
    company: '',
    title: 'OPEN',
    speakerIds: [],
    isSponsored: false,
    isTbd: true,
    notes: '',
  },
];

export function createInitialState(): AppState {
  return {
    version: 1,
    days: SEED_DAYS,
    venues: SEED_VENUES,
    slots: SEED_SLOTS,
    contacts: SEED_CONTACTS,
    lastModified: new Date().toISOString(),
  };
}
