import type { TimeSlot, Contact, ScheduleDay, Venue, AppState } from '../types/schedule';
import { timeToSlot, durationToSlots } from '../utils/time';

const SEED_DAYS: ScheduleDay[] = [
  { id: 'wed', label: 'Wed 5/27 — Load-In', date: '2025-05-27' },
  { id: 'thu', label: 'Thu 5/28', date: '2025-05-28' },
  { id: 'fri', label: 'Fri 5/29', date: '2025-05-29' },
];

const SEED_VENUES: Venue[] = [
  { id: 'main-stage', label: 'Main Stage' },
  { id: 'll-a', label: 'LL-A' },
  { id: 'll-b', label: 'LL-B' },
];

// === Contact IDs (stable so slot references work) ===
const C = {
  ehren:       'c-ehren-stanhope',
  chris:       'c-chris-loveless',
  joeGiroux:   'c-joe-giroux',
  ryan:        'c-ryan-kirlin',
  robArnott:   'c-rob-arnott',
  jeffChang:   'c-jeff-chang',
  danielBunn:  'c-daniel-bunn',
  josephAqr:   'c-joseph-liberman',
  alex:        'c-alex-fm',
  nuveen:      'c-nuveen-brooklyn',
  savina:      'c-savina-rizova',
  meb:         'c-meb-faber',
  paulB:       'c-paul-bouchey',
  andrewBeer:  'c-andrew-beer',
  daveNadig:   'c-dave-nadig',
  shangChou:   'c-shang-chou',
  keenan:      'c-keenan-szulik',
  jimCarroll:  'c-jim-carroll',
  terryCook:   'c-terry-cook',
  nickR:       'c-nick-rosenthal',
  robertD:     'c-robert-dupree',
  jimDubeck:   'c-jim-dubeck',
  johnWest:    'c-john-west',
  ralphD:      'c-ralph-drybrough',
  royHaya:     'c-roy-haya',
  thomasB:     'c-thomas-boczar',
  mikeAllison: 'c-mike-allison',
  rafaelZ:     'c-rafael-zayas',
  jonFT:       'c-jon-ft',
  daveReynolds:'c-dave-reynolds',
  michaelL:    'c-michael-liebeskind',
  mohsenG:     'c-mohsen-ghazi',
  ericGolden:  'c-eric-golden',
};

const SEED_CONTACTS: Contact[] = [
  // --- Canvas ---
  { id: C.ehren, name: 'Ehren Stanhope', company: 'Canvas', title: 'Chief Investment Strategist', email: 'ehren.stanhope@osam.com', phone: '', supportName: '', supportEmail: '', supportPhone: '', notes: '' },
  { id: C.chris, name: 'Chris Loveless', company: 'Canvas', title: 'President', email: 'chris.loveless@osam.com', phone: '', supportName: 'Laura Kelleher', supportEmail: 'laura.kelleher@osam.com', supportPhone: '', notes: '' },
  { id: C.joeGiroux, name: 'Joe Giroux', company: 'Canvas', title: 'Portfolio Manager', email: 'joe.giroux@osam.com', phone: '', supportName: '', supportEmail: '', supportPhone: '', notes: '' },

  // --- Speakers ---
  { id: C.ryan, name: 'Ryan Patrick Kirlin', company: 'Alpha Architect', title: 'President', email: 'ryan@alphaarchitect.com', phone: '', supportName: '', supportEmail: '', supportPhone: '', notes: '' },
  { id: C.robArnott, name: 'Rob Arnott', company: 'Research Affiliates', title: 'Founder & Chairman', email: 'arnott@rallc.com', phone: '', supportName: 'Brent Leadbetter', supportEmail: 'leadbetter@rallc.com', supportPhone: '', notes: 'Will send PPT closer to event' },
  { id: C.jeffChang, name: 'Jeff Chang', company: 'First Trust', title: '', email: 'jchang@vestfin.com', phone: '', supportName: 'Brianna Fessler', supportEmail: 'bfessler@vestfin.com', supportPhone: '', notes: '' },
  { id: C.danielBunn, name: 'Daniel Bunn', company: 'Tax Foundation', title: 'President & CEO', email: 'dbunn@taxfoundation.org', phone: '', supportName: 'Katelynn Barbosa', supportEmail: 'kbarbosa@taxfoundation.org', supportPhone: '', notes: 'VIP' },
  { id: C.josephAqr, name: 'Joseph Liberman', company: 'AQR', title: 'Managing Director Quantitative Research', email: 'Joseph.Liberman@aqr.com', phone: '', supportName: 'Dan Villalon', supportEmail: 'Dan.Villalon@aqr.com', supportPhone: '', notes: '' },
  { id: C.alex, name: 'Alex Morris', company: 'f/m Investments', title: '', email: 'amorris@fminvest.com', phone: '', supportName: 'Courtney Sheehy', supportEmail: 'csheehy@fminvest.com', supportPhone: '', notes: '' },
  { id: C.savina, name: 'Savina Rizova', company: 'Dimensional Fund Advisors', title: 'Co-Chief Investment Officer', email: 'Savina.Rizova@dimensional.com', phone: '', supportName: 'Taylor Smith / Kacie Walsh', supportEmail: 'Taylor.Smith@dimensional.com, Kacie.Walsh@dimensional.com', supportPhone: '', notes: '' },
  { id: C.meb, name: 'Meb Faber', company: 'Cambria', title: '', email: '', phone: '', supportName: '', supportEmail: '', supportPhone: '', notes: 'Kai sent email requesting session title' },
  { id: C.paulB, name: 'Paul Bouchey', company: 'Parametric (Morgan Stanley)', title: 'Managing Director Applied Research / Former CIO', email: 'paul.bouchey@gmail.com', phone: '', supportName: '', supportEmail: '', supportPhone: '', notes: '' },
  { id: C.andrewBeer, name: 'Andrew Beer', company: 'DBi', title: 'Managing Member', email: 'a@dbi.co', phone: '', supportName: '', supportEmail: '', supportPhone: '', notes: '' },
  { id: C.jonFT, name: 'Jon', company: 'First Trust', title: '', email: '', phone: '', supportName: '', supportEmail: '', supportPhone: '', notes: 'Fri main panel' },

  // --- Emcees ---
  { id: C.shangChou, name: 'Shang Chou', company: 'Dishmi', title: 'Managing Partner', email: 'shang@dishmicap.com', phone: '', supportName: '', supportEmail: '', supportPhone: '', notes: 'Emcee as needed both days' },
  { id: C.daveNadig, name: 'Dave Nadig', company: 'ETF.com', title: 'President & Director of Research', email: 'dave@etf.com', phone: '', supportName: '', supportEmail: '', supportPhone: '', notes: 'Emcee as needed' },

  // --- Panelists ---
  { id: C.keenan, name: 'Keenan Szulik', company: 'Slocum Management', title: 'CEO', email: 'kszulik8@gmail.com', phone: '', supportName: '', supportEmail: '', supportPhone: '', notes: 'Practitioner Group Host' },
  { id: C.jimCarroll, name: 'Jim Carroll', company: 'Ballast Rock', title: '', email: 'jim.carroll@ballastrockpw.com', phone: '', supportName: '', supportEmail: '', supportPhone: '', notes: 'Investment flexibility of SMAs for PPLI' },
  { id: C.terryCook, name: 'Terry Cook', company: 'Parcion', title: 'Co-CEO', email: 'terry@parcionpw.com', phone: '', supportName: '', supportEmail: '', supportPhone: '', notes: 'OZ Panel' },
  { id: C.nickR, name: 'Nick Rosenthal', company: 'Griffin Capital', title: 'Principal', email: 'nrosenthal@griffincapital.com', phone: '', supportName: 'Matt Cardall', supportEmail: 'mcardall@cimgroup.com', supportPhone: '', notes: 'OZ Panel' },
  { id: C.robertD, name: 'Robert Dupree', company: 'CIM Group', title: 'Co-Head of Infrastructure', email: 'rdupree@cimgroup.com', phone: '', supportName: '', supportEmail: '', supportPhone: '', notes: 'OZ Panel' },
  { id: C.jimDubeck, name: 'Jim Dubeck', company: 'Moss Adams', title: '', email: 'jim.dubeck@mossadams.com', phone: '', supportName: '', supportEmail: '', supportPhone: '', notes: 'OZ Panel' },
  { id: C.johnWest, name: 'John West', company: 'RE/Arqitel', title: '', email: '', phone: '', supportName: '', supportEmail: '', supportPhone: '', notes: '' },
  { id: C.ralphD, name: 'Ralph Drybrough', company: 'Fort Point Capital', title: 'Managing Partner', email: 'rd@fortpointcap.com', phone: '', supportName: '', supportEmail: '', supportPhone: '', notes: '' },
  { id: C.royHaya, name: 'Roy Haya', company: 'Fort Point Capital', title: 'Head of Derivative Solutions', email: 'rh@fortpointcap.com', phone: '', supportName: '', supportEmail: '', supportPhone: '', notes: '' },
  { id: C.thomasB, name: 'Thomas Boczar', company: 'Consultant', title: '', email: 'thomas.boczar@outlook.com', phone: '', supportName: '', supportEmail: '', supportPhone: '', notes: '' },
  { id: C.mikeAllison, name: 'Mike Allison', company: 'IRP', title: 'Strategist & Portfolio Manager', email: 'mike@investmentresearchpartners.com', phone: '', supportName: '', supportEmail: '', supportPhone: '', notes: '' },
  { id: C.rafaelZ, name: 'Rafael Zayas', company: '', title: '', email: '', phone: '', supportName: '', supportEmail: '', supportPhone: '', notes: '351 Panel' },

  // --- PPLI Panel ---
  { id: C.daveReynolds, name: 'Dave Reynolds', company: 'Spearhead', title: '', email: '', phone: '', supportName: '', supportEmail: '', supportPhone: '', notes: 'Largest SMA platform for PPLI. PPLI Panel Moderator.' },
  { id: C.michaelL, name: 'Michael Liebeskind', company: 'Golconda', title: '', email: '', phone: '', supportName: '', supportEmail: '', supportPhone: '', notes: 'Power of the PPLI structure' },
  { id: C.mohsenG, name: 'Mohsen Ghazi', company: '', title: '', email: '', phone: '', supportName: '', supportEmail: '', supportPhone: '', notes: 'Family office use cases for PPLI' },
  { id: C.ericGolden, name: 'Eric Golden', company: '', title: '', email: '', phone: '', supportName: '', supportEmail: '', supportPhone: '', notes: 'Fixed income panel with Dave Nadig' },
];

const SEED_SLOTS: TimeSlot[] = [
  // ===== WEDNESDAY — Load-In =====
  {
    id: 'wed-main-loadin',
    dayId: 'wed',
    venueId: 'main-stage',
    startSlot: timeToSlot(9, 0),
    durationSlots: durationToSlots(480),
    type: 'load-in',
    company: '',
    title: 'Load in (Fern & Staff)',
    assignments: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'wed-expo-loadin',
    dayId: 'wed',
    venueId: 'll-a',
    startSlot: timeToSlot(12, 0),
    durationSlots: durationToSlots(300),
    type: 'load-in',
    company: '',
    title: 'Load in (Expos)',
    assignments: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'wed-canvas-dinner',
    dayId: 'wed',
    venueId: 'main-stage',
    startSlot: timeToSlot(17, 0),
    durationSlots: durationToSlots(120),
    type: 'event',
    company: 'Canvas',
    title: 'Canvas Dinner @ Aerlume',
    assignments: [],
    isSponsored: true,
    isTbd: false,
    notes: 'Aerlume, 2003 Western Ave, Seattle. Near Pier 66 / waterfront. 5-7 PM. Hosted by Canvas.',
  },

  // ===== THURSDAY — Day 1: Main Stage =====
  {
    id: 'thu-main-doors',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(7, 15),
    durationSlots: durationToSlots(15),
    type: 'event',
    company: '',
    title: 'Doors & Registration',
    assignments: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'thu-main-breakfast',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(7, 30),
    durationSlots: durationToSlots(60),
    type: 'event',
    company: '',
    title: 'Breakfast + Expo',
    assignments: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'thu-main-opening-remarks',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(8, 30),
    durationSlots: durationToSlots(5),
    type: 'event',
    company: 'Canvas',
    title: 'Welcome Remarks',
    assignments: [{ contactId: C.chris, slotRole: 'Speaker' }],
    isSponsored: true,
    isTbd: false,
    notes: '',
  },
  {
    id: 'thu-main-keynote1',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(8, 35),
    durationSlots: durationToSlots(25),
    type: 'keynote',
    company: 'Canvas',
    title: 'Taxable Wealth: From Core Strategies to Cutting Edge Solutions',
    assignments: [{ contactId: C.ehren, slotRole: 'Speaker' }],
    isSponsored: true,
    isTbd: false,
    notes: '',
  },
  {
    id: 'thu-main-arnott',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(9, 0),
    durationSlots: durationToSlots(25),
    type: 'solo',
    company: 'Research Affiliates',
    title: 'Index Solutions for Tax Alpha Portfolios',
    assignments: [{ contactId: C.robArnott, slotRole: 'Speaker' }],
    isSponsored: false,
    isTbd: false,
    notes: 'Will send PPT closer to event',
  },
  {
    id: 'thu-main-break1',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(9, 30),
    durationSlots: durationToSlots(15),
    type: 'break',
    company: '',
    title: 'BREAK',
    assignments: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'thu-main-ryan',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(9, 45),
    durationSlots: durationToSlots(25),
    type: 'solo',
    company: 'Alpha Architect',
    title: 'What is a Syndic?',
    assignments: [{ contactId: C.ryan, slotRole: 'Speaker' }],
    isSponsored: true,
    isTbd: false,
    notes: '351 exchanges are a hot topic',
  },
  {
    id: 'thu-main-jeff',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(10, 15),
    durationSlots: durationToSlots(40),
    type: 'solo',
    company: 'First Trust',
    title: '',
    assignments: [{ contactId: C.jeffChang, slotRole: 'Speaker' }],
    isSponsored: true,
    isTbd: true,
    notes: 'Session title TBD',
  },
  {
    id: 'thu-main-open1',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(11, 0),
    durationSlots: durationToSlots(30),
    type: 'open',
    company: '',
    title: 'OPEN',
    assignments: [],
    isSponsored: false,
    isTbd: true,
    notes: '',
  },
  {
    id: 'thu-main-lunch',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(11, 30),
    durationSlots: durationToSlots(105),
    type: 'event',
    company: '',
    title: 'Lunch / Expo',
    assignments: [],
    isSponsored: false,
    isTbd: false,
    notes: '30 dedicated / 1.5 food available',
  },
  {
    id: 'thu-main-alex',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(13, 15),
    durationSlots: durationToSlots(25),
    type: 'solo',
    company: 'f/m Investments',
    title: '',
    assignments: [{ contactId: C.alex, slotRole: 'Speaker' }],
    isSponsored: true,
    isTbd: true,
    notes: 'Session title TBD',
  },
  {
    id: 'thu-main-bunn',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(13, 45),
    durationSlots: durationToSlots(25),
    type: 'solo',
    company: 'Tax Foundation',
    title: '',
    assignments: [{ contactId: C.danielBunn, slotRole: 'Speaker' }],
    isSponsored: false,
    isTbd: true,
    notes: 'VIP. Session title TBD.',
  },
  {
    id: 'thu-main-break2',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(14, 15),
    durationSlots: durationToSlots(15),
    type: 'break',
    company: '',
    title: 'BREAK',
    assignments: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'thu-main-aqr',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(14, 30),
    durationSlots: durationToSlots(25),
    type: 'solo',
    company: 'AQR',
    title: '',
    assignments: [{ contactId: C.josephAqr, slotRole: 'Speaker' }],
    isSponsored: false,
    isTbd: true,
    notes: 'Session title TBD',
  },
  {
    id: 'thu-main-aqr-fort',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(15, 0),
    durationSlots: durationToSlots(25),
    type: 'solo',
    company: 'AQR / Fort Point',
    title: '',
    assignments: [{ contactId: C.ralphD, slotRole: 'Speaker' }, { contactId: C.royHaya, slotRole: 'Speaker' }],
    isSponsored: false,
    isTbd: true,
    notes: 'Ralph Drybrough & Roy Haya. Back-to-back with AQR, possible friendly overlap. Session title TBD.',
  },
  {
    id: 'thu-main-break3',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(15, 30),
    durationSlots: durationToSlots(15),
    type: 'break',
    company: '',
    title: 'BREAK',
    assignments: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'thu-main-nuveen',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(15, 45),
    durationSlots: durationToSlots(25),
    type: 'panel',
    company: 'Nuveen / Brooklyn',
    title: '',
    assignments: [],
    isSponsored: true,
    isTbd: true,
    notes: 'Panel members TBD',
  },
  {
    id: 'thu-main-alliance',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(16, 15),
    durationSlots: durationToSlots(25),
    type: 'solo',
    company: 'Alliance',
    title: '',
    assignments: [],
    isSponsored: false,
    isTbd: true,
    notes: 'Speaker TBD',
  },
  {
    id: 'thu-main-ft-closer',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(16, 45),
    durationSlots: durationToSlots(5),
    type: 'event',
    company: 'First Trust',
    title: 'FT Closing Remarks',
    assignments: [],
    isSponsored: true,
    isTbd: false,
    notes: 'First Trust hosting the happy hour',
  },
  {
    id: 'thu-main-hh',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(16, 50),
    durationSlots: durationToSlots(130),
    type: 'event',
    company: 'First Trust',
    title: 'Thursday Happy Hour',
    assignments: [],
    isSponsored: true,
    isTbd: false,
    notes: 'Hosted by First Trust',
  },
  {
    id: 'thu-main-nuveen-dinner',
    dayId: 'thu',
    venueId: 'll-b',
    startSlot: timeToSlot(19, 0),
    durationSlots: durationToSlots(120),
    type: 'event',
    company: 'Nuveen / Brooklyn',
    title: 'Dinner (Offsite)',
    assignments: [],
    isSponsored: true,
    isTbd: true,
    notes: 'TBD offsite location. 7-9 PM.',
  },

  // ===== THURSDAY — LL-A Breakout =====
  {
    id: 'thu-lla-pimco',
    dayId: 'thu',
    venueId: 'll-a',
    startSlot: timeToSlot(12, 0),
    durationSlots: durationToSlots(20),
    type: 'solo',
    company: 'PIMCO',
    title: '',
    assignments: [],
    isSponsored: false,
    isTbd: true,
    notes: 'PIMCO #1 — speaker TBD',
  },
  {
    id: 'thu-lla-351',
    dayId: 'thu',
    venueId: 'll-a',
    startSlot: timeToSlot(12, 30),
    durationSlots: durationToSlots(20),
    type: 'panel',
    company: '',
    title: '351 Panel',
    assignments: [{ contactId: C.johnWest, slotRole: 'Moderator' }, { contactId: C.meb, slotRole: 'Speaker' }, { contactId: C.ryan, slotRole: 'Speaker' }, { contactId: C.rafaelZ, slotRole: 'Speaker' }],
    isSponsored: true,
    isTbd: false,
    notes: 'Moderator: John West. Panelists: Meb Faber, Ryan Kirlin, Rafael Zayas, TBD someone from Scharf. Ask Dorothy Friedrich dorothy@scharfinvestments.com',
  },

  // ===== THURSDAY — LL-B Breakout =====
  {
    id: 'thu-llb-oz',
    dayId: 'thu',
    venueId: 'll-b',
    startSlot: timeToSlot(12, 0),
    durationSlots: durationToSlots(25),
    type: 'panel',
    company: 'OZ / Griffin Capital / CIM Group',
    title: '',
    assignments: [{ contactId: C.terryCook, slotRole: 'Speaker' }, { contactId: C.nickR, slotRole: 'Speaker' }, { contactId: C.robertD, slotRole: 'Speaker' }, { contactId: C.jimDubeck, slotRole: 'Speaker' }],
    isSponsored: false,
    isTbd: true,
    notes: 'Nick said he\'ll let Terry decide the Session Title (4/1). Support: Matt Cardall mcardall@cimgroup.com',
  },
  {
    id: 'thu-llb-johnwest',
    dayId: 'thu',
    venueId: 'll-b',
    startSlot: timeToSlot(12, 30),
    durationSlots: durationToSlots(20),
    type: 'solo',
    company: 'RE/Arqitel',
    title: '',
    assignments: [{ contactId: C.johnWest, slotRole: 'Speaker' }],
    isSponsored: false,
    isTbd: true,
    notes: 'Session title TBD',
  },

  // ===== FRIDAY — Day 2: Main Stage =====
  {
    id: 'fri-main-doors',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(7, 15),
    durationSlots: durationToSlots(15),
    type: 'event',
    company: '',
    title: 'Doors & Registration',
    assignments: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'fri-main-vip-breakfast',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(7, 30),
    durationSlots: durationToSlots(75),
    type: 'event',
    company: '',
    title: 'VIP Breakfast',
    assignments: [],
    isSponsored: false,
    isTbd: false,
    notes: '7:30-8:45 AM',
  },
  {
    id: 'fri-main-panel8',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(9, 0),
    durationSlots: durationToSlots(25),
    type: 'keynote',
    company: 'Canvas',
    title: 'AMA: Canvas and Coffee and Everything Taxable Wealth In Between',
    assignments: [{ contactId: C.joeGiroux, slotRole: 'Speaker' }],
    isSponsored: true,
    isTbd: false,
    notes: '',
  },
  {
    id: 'fri-main-savina',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(9, 30),
    durationSlots: durationToSlots(25),
    type: 'solo',
    company: 'Dimensional Fund Advisors',
    title: 'Long-Only and Long-Short SMAs – The Dimensional Perspective',
    assignments: [{ contactId: C.savina, slotRole: 'Speaker' }],
    isSponsored: false,
    isTbd: false,
    notes: 'Support: Taylor.Smith@dimensional.com, Kacie.Walsh@dimensional.com',
  },
  {
    id: 'fri-main-savina-panel',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(10, 0),
    durationSlots: durationToSlots(15),
    type: 'panel',
    company: '',
    title: 'Panel w/ Savina',
    assignments: [{ contactId: C.savina, slotRole: 'Speaker' }],
    isSponsored: false,
    isTbd: true,
    notes: 'Panel details TBD',
  },
  {
    id: 'fri-main-break1',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(10, 15),
    durationSlots: durationToSlots(10),
    type: 'break',
    company: '',
    title: 'BREAK',
    assignments: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'fri-main-firsttrust',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(10, 25),
    durationSlots: durationToSlots(25),
    type: 'panel',
    company: 'First Trust',
    title: '',
    assignments: [{ contactId: C.jonFT, slotRole: 'Speaker' }],
    isSponsored: true,
    isTbd: true,
    notes: 'First Trust Panel — Christian + who else? TBD',
  },
  {
    id: 'fri-main-open-1050',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(10, 50),
    durationSlots: durationToSlots(35),
    type: 'open',
    company: '',
    title: 'OPEN — Sponsorship Available',
    assignments: [],
    isSponsored: false,
    isTbd: true,
    notes: 'High-value main stage slot. 35 min.',
  },
  {
    id: 'fri-main-lunch',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(11, 30),
    durationSlots: durationToSlots(90),
    type: 'event',
    company: '',
    title: 'Lunch / Expo',
    assignments: [],
    isSponsored: false,
    isTbd: false,
    notes: '20 min dedicated',
  },
  {
    id: 'fri-main-open-1250',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(12, 50),
    durationSlots: durationToSlots(40),
    type: 'open',
    company: '',
    title: 'OPEN',
    assignments: [],
    isSponsored: false,
    isTbd: true,
    notes: 'Longview (30) - TBD',
  },
  {
    id: 'fri-main-practitioner',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(13, 30),
    durationSlots: durationToSlots(45),
    type: 'panel',
    company: 'Slocum Management',
    title: 'Live from the Field: Tax Aware Long-Short Working Group',
    assignments: [{ contactId: C.keenan, slotRole: 'Moderator' }],
    isSponsored: false,
    isTbd: false,
    notes: 'Practitioner Group. Brent Long-Short host.',
  },
  {
    id: 'fri-main-paul-ms',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(14, 15),
    durationSlots: durationToSlots(30),
    type: 'solo',
    company: 'Parametric (Morgan Stanley)',
    title: '',
    assignments: [{ contactId: C.paulB, slotRole: 'Speaker' }],
    isSponsored: true,
    isTbd: true,
    notes: 'Session title TBD',
  },
  {
    id: 'fri-main-break2',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(14, 45),
    durationSlots: durationToSlots(15),
    type: 'break',
    company: '',
    title: 'BREAK',
    assignments: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'fri-main-beer',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(15, 0),
    durationSlots: durationToSlots(30),
    type: 'solo',
    company: 'DBi',
    title: '',
    assignments: [{ contactId: C.andrewBeer, slotRole: 'Speaker' }],
    isSponsored: false,
    isTbd: true,
    notes: 'Session title TBD',
  },
  {
    id: 'fri-main-nadig',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(15, 30),
    durationSlots: durationToSlots(30),
    type: 'solo',
    company: 'ETF.com',
    title: '',
    assignments: [{ contactId: C.daveNadig, slotRole: 'Speaker' }],
    isSponsored: false,
    isTbd: true,
    notes: 'Session title TBD',
  },
  {
    id: 'fri-main-break3',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(16, 0),
    durationSlots: durationToSlots(15),
    type: 'break',
    company: '',
    title: 'BREAK',
    assignments: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'fri-main-vise',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(16, 15),
    durationSlots: durationToSlots(25),
    type: 'solo',
    company: 'Vise',
    title: '',
    assignments: [],
    isSponsored: false,
    isTbd: true,
    notes: 'Runik TBD',
  },
  {
    id: 'fri-main-meb',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(16, 45),
    durationSlots: durationToSlots(25),
    type: 'solo',
    company: 'Cambria',
    title: '',
    assignments: [{ contactId: C.meb, slotRole: 'Speaker' }],
    isSponsored: true,
    isTbd: true,
    notes: 'Final presentation Day 2. Session title TBD.',
  },
  {
    id: 'fri-main-closing',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(17, 10),
    durationSlots: durationToSlots(5),
    type: 'event',
    company: '',
    title: 'Thanks for Coming — Brent Closing',
    assignments: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'fri-main-mariners',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(17, 15),
    durationSlots: durationToSlots(165),
    type: 'event',
    company: '',
    title: 'Mariners vs Diamondbacks @ T-Mobile Park',
    assignments: [],
    isSponsored: false,
    isTbd: false,
    notes: 'First pitch 7:10 PM PT. Group outing.',
  },

  // ===== FRIDAY — LL-A Breakout =====
  {
    id: 'fri-lla-wealth',
    dayId: 'fri',
    venueId: 'll-a',
    startSlot: timeToSlot(11, 50),
    durationSlots: durationToSlots(20),
    type: 'panel',
    company: '',
    title: 'Single Stock Panel',
    assignments: [{ contactId: C.shangChou, slotRole: 'Moderator' }, { contactId: C.mikeAllison, slotRole: 'Speaker' }],
    isSponsored: false,
    isTbd: false,
    notes: 'Shang Chou running panel. Mike Allison only confirmed panelist so far.',
  },
  {
    id: 'fri-lla-pimco',
    dayId: 'fri',
    venueId: 'll-a',
    startSlot: timeToSlot(12, 20),
    durationSlots: durationToSlots(20),
    type: 'solo',
    company: 'PIMCO',
    title: '',
    assignments: [],
    isSponsored: false,
    isTbd: true,
    notes: 'PIMCO #2 — speaker TBD',
  },
  {
    id: 'fri-lla-fi-panel',
    dayId: 'fri',
    venueId: 'll-a',
    startSlot: timeToSlot(12, 50),
    durationSlots: durationToSlots(20),
    type: 'panel',
    company: '',
    title: 'Tax-Efficient Fixed Income. Yes.',
    assignments: [{ contactId: C.daveNadig, slotRole: 'Speaker' }, { contactId: C.ericGolden, slotRole: 'Speaker' }],
    isSponsored: false,
    isTbd: true,
    notes: 'Title TBD. Dave Nadig + Eric Golden.',
  },
  {
    id: 'fri-lla-open2',
    dayId: 'fri',
    venueId: 'll-a',
    startSlot: timeToSlot(13, 30),
    durationSlots: durationToSlots(40),
    type: 'panel',
    company: 'Fort Point Capital',
    title: '',
    assignments: [{ contactId: C.ralphD, slotRole: 'Speaker' }, { contactId: C.royHaya, slotRole: 'Speaker' }, { contactId: C.thomasB, slotRole: 'Speaker' }],
    isSponsored: false,
    isTbd: true,
    notes: 'Ralph Drybrough, Roy Haya, Thomas Boczar. Session title TBD.',
  },

  // ===== FRIDAY — LL-B Breakout =====
  {
    id: 'fri-llb-ppli',
    dayId: 'fri',
    venueId: 'll-b',
    startSlot: timeToSlot(11, 50),
    durationSlots: durationToSlots(20),
    type: 'panel',
    company: 'PPLI',
    title: '',
    assignments: [{ contactId: C.daveReynolds, slotRole: 'Moderator' }, { contactId: C.michaelL, slotRole: 'Speaker' }, { contactId: C.jimCarroll, slotRole: 'Speaker' }, { contactId: C.mohsenG, slotRole: 'Speaker' }],
    isSponsored: false,
    isTbd: true,
    notes: 'Moderator: Dave Reynolds (Spearhead). Michael Liebeskind (Golconda) — power of PPLI structure. Jim Carroll — investment flexibility of SMAs for PPLI. Mohsen Ghazi — family office use cases.',
  },
  {
    id: 'fri-llb-open1',
    dayId: 'fri',
    venueId: 'll-b',
    startSlot: timeToSlot(12, 20),
    durationSlots: durationToSlots(20),
    type: 'open',
    company: '',
    title: 'OPEN',
    assignments: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'fri-llb-open2',
    dayId: 'fri',
    venueId: 'll-b',
    startSlot: timeToSlot(12, 50),
    durationSlots: durationToSlots(20),
    type: 'open',
    company: '',
    title: 'OPEN',
    assignments: [],
    isSponsored: false,
    isTbd: true,
    notes: '',
  },
];

export function createInitialState(): AppState {
  return {
    version: 1,
    days: SEED_DAYS,
    venues: SEED_VENUES,
    slots: SEED_SLOTS,
    contacts: SEED_CONTACTS,
    lastModified: new Date().toISOString(),
  };
}
