import type { TimeSlot, Contact, ScheduleDay, Venue, AppState } from '../types/schedule';
import { timeToSlot, durationToSlots } from '../utils/time';

const SEED_DAYS: ScheduleDay[] = [
  { id: 'wed', label: 'Wed 5/27 — Load-In', date: '2025-05-27' },
  { id: 'thu', label: 'Thu 5/28 — Day 1', date: '2025-05-28' },
  { id: 'fri', label: 'Fri 5/29 — Day 2', date: '2025-05-29' },
];

const SEED_VENUES: Venue[] = [
  { id: 'main-stage', label: 'Main Stage' },
  { id: 'll-a', label: 'LL-A' },
  { id: 'll-b', label: 'LL-B' },
];

const SEED_SLOTS: TimeSlot[] = [
  // ===== WEDNESDAY — Load-In =====
  {
    id: 'wed-main-loadin',
    dayId: 'wed',
    venueId: 'main-stage',
    startSlot: timeToSlot(9, 0),
    durationSlots: durationToSlots(480), // 9am-5pm
    type: 'load-in',
    company: '',
    title: 'Load in (Fern & Staff)',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'wed-expo-loadin',
    dayId: 'wed',
    venueId: 'll-a',
    startSlot: timeToSlot(12, 0),
    durationSlots: durationToSlots(300), // 12pm-5pm
    type: 'load-in',
    company: '',
    title: 'Load in (Expos)',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'wed-opening-hh',
    dayId: 'wed',
    venueId: 'main-stage',
    startSlot: timeToSlot(17, 0),
    durationSlots: durationToSlots(60),
    type: 'event',
    company: '',
    title: 'Opening HH (Canvas)',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },

  // ===== THURSDAY — Day 1: Main Stage =====
  {
    id: 'thu-main-doors',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(7, 15),
    durationSlots: durationToSlots(15),
    type: 'event',
    company: '',
    title: 'Doors & Registration',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'thu-main-breakfast',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(7, 30),
    durationSlots: durationToSlots(60),
    type: 'event',
    company: '',
    title: 'Breakfast + Expo',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'thu-main-keynote1',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(8, 30),
    durationSlots: durationToSlots(25),
    type: 'keynote',
    company: 'Canvas',
    title: '#1 Canvas Keynote',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: 'If (25) = Agenda will reflect 30 min timing',
  },
  {
    id: 'thu-main-arnott',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(9, 0),
    durationSlots: durationToSlots(25),
    type: 'solo',
    company: '',
    title: '#2 Rob Arnott',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'thu-main-break1',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(9, 30),
    durationSlots: durationToSlots(15),
    type: 'break',
    company: '',
    title: 'BREAK',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'thu-main-ryan',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(9, 45),
    durationSlots: durationToSlots(25),
    type: 'solo',
    company: '',
    title: '#3 Ryan / Alpha',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'thu-main-jeff',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(10, 15),
    durationSlots: durationToSlots(40),
    type: 'solo',
    company: '',
    title: '#5 Jeff Chang + Jon',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'thu-main-open1',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(11, 0),
    durationSlots: durationToSlots(30),
    type: 'open',
    company: '',
    title: 'OPEN',
    speakerIds: [],
    isSponsored: false,
    isTbd: true,
    notes: '',
  },
  {
    id: 'thu-main-lunch',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(11, 30),
    durationSlots: durationToSlots(105), // 11:30-1:15
    type: 'event',
    company: '',
    title: 'Lunch / Expo',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '30 dedicated / 1.5 food available',
  },
  {
    id: 'thu-main-alex',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(13, 15),
    durationSlots: durationToSlots(25),
    type: 'solo',
    company: '',
    title: '#12 Alex / F/m',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'thu-main-bunn',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(13, 45),
    durationSlots: durationToSlots(25),
    type: 'solo',
    company: '',
    title: '#4 Daniel Bunn',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'thu-main-break2',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(14, 15),
    durationSlots: durationToSlots(15),
    type: 'break',
    company: '',
    title: 'BREAK',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'thu-main-aqr',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(14, 30),
    durationSlots: durationToSlots(25),
    type: 'solo',
    company: '',
    title: '#7 AQR',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'thu-main-aqr-fort',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(15, 0),
    durationSlots: durationToSlots(25),
    type: 'solo',
    company: '',
    title: 'AQR/Fort Point',
    speakerIds: [],
    isSponsored: false,
    isTbd: true,
    notes: 'TBD',
  },
  {
    id: 'thu-main-break3',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(15, 30),
    durationSlots: durationToSlots(15),
    type: 'break',
    company: '',
    title: 'BREAK',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'thu-main-nuveen',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(15, 45),
    durationSlots: durationToSlots(25),
    type: 'panel',
    company: '',
    title: '#6 Nuveen Panel',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'thu-main-alliance',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(16, 15),
    durationSlots: durationToSlots(25),
    type: 'solo',
    company: '',
    title: 'Alliance',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'thu-main-closing',
    dayId: 'thu',
    venueId: 'main-stage',
    startSlot: timeToSlot(16, 45),
    durationSlots: durationToSlots(45),
    type: 'event',
    company: '',
    title: 'FT Closing + Thu HH (FT)',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },

  // ===== THURSDAY — LL-A Breakout =====
  {
    id: 'thu-lla-pimco',
    dayId: 'thu',
    venueId: 'll-a',
    startSlot: timeToSlot(12, 0),
    durationSlots: durationToSlots(20),
    type: 'solo',
    company: '',
    title: 'PIMCO',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'thu-lla-351',
    dayId: 'thu',
    venueId: 'll-a',
    startSlot: timeToSlot(12, 30),
    durationSlots: durationToSlots(20),
    type: 'panel',
    company: '',
    title: '351 Panel',
    speakerIds: [],
    isSponsored: true,
    isTbd: false,
    notes: 'Sponsored?',
  },

  // ===== THURSDAY — LL-B Breakout =====
  {
    id: 'thu-llb-oz',
    dayId: 'thu',
    venueId: 'll-b',
    startSlot: timeToSlot(12, 0),
    durationSlots: durationToSlots(20),
    type: 'panel',
    company: '',
    title: 'OZ Panel',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'thu-llb-johnwest',
    dayId: 'thu',
    venueId: 'll-b',
    startSlot: timeToSlot(12, 30),
    durationSlots: durationToSlots(20),
    type: 'solo',
    company: '',
    title: 'John West RE/Arqitel',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },

  // ===== FRIDAY — Day 2: Main Stage =====
  {
    id: 'fri-main-doors',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(7, 15),
    durationSlots: durationToSlots(15),
    type: 'event',
    company: '',
    title: 'Doors & Registration',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'fri-main-breakfast',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(7, 30),
    durationSlots: durationToSlots(60),
    type: 'event',
    company: '',
    title: 'Breakfast + Expo',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'fri-main-panel8',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(8, 30),
    durationSlots: durationToSlots(25),
    type: 'panel',
    company: '',
    title: '#8 Canvas Panel',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'fri-main-savina',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(9, 0),
    durationSlots: durationToSlots(25),
    type: 'solo',
    company: '',
    title: '#9 Savina / DFA',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'fri-main-savina-panel',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(9, 30),
    durationSlots: durationToSlots(15),
    type: 'panel',
    company: '',
    title: 'Panel - TBD w/ Savina',
    speakerIds: [],
    isSponsored: false,
    isTbd: true,
    notes: '',
  },
  {
    id: 'fri-main-break1',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(10, 0),
    durationSlots: durationToSlots(15),
    type: 'break',
    company: '',
    title: 'BREAK',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'fri-main-firsttrust',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(10, 15),
    durationSlots: durationToSlots(25),
    type: 'panel',
    company: '',
    title: '#10 First Trust Panel (Christian)',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'fri-main-meb',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(10, 45),
    durationSlots: durationToSlots(25),
    type: 'solo',
    company: '',
    title: 'Meb Faber',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: 'Checking with Meb about if he can be end of day',
  },
  {
    id: 'fri-main-lunch',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(11, 30),
    durationSlots: durationToSlots(90), // 11:30-1:00
    type: 'event',
    company: '',
    title: 'Lunch / Expo',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '20 min dedicated',
  },
  {
    id: 'fri-main-open-1250',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(12, 50),
    durationSlots: durationToSlots(40),
    type: 'open',
    company: '',
    title: 'OPEN',
    speakerIds: [],
    isSponsored: false,
    isTbd: true,
    notes: 'Longview (30) - TBD',
  },
  {
    id: 'fri-main-practitioner',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(13, 30),
    durationSlots: durationToSlots(45),
    type: 'panel',
    company: '',
    title: 'Practitioner Group',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'fri-main-paul-ms',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(14, 15),
    durationSlots: durationToSlots(30),
    type: 'solo',
    company: '',
    title: 'Paul / MS',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'fri-main-break2',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(14, 45),
    durationSlots: durationToSlots(15),
    type: 'break',
    company: '',
    title: 'BREAK',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'fri-main-beer',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(15, 0),
    durationSlots: durationToSlots(30),
    type: 'solo',
    company: '',
    title: '#13 Andrew Beer / Simplify',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'fri-main-nadig',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(15, 30),
    durationSlots: durationToSlots(30),
    type: 'solo',
    company: '',
    title: 'Dave Nadig',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'fri-main-break3',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(16, 0),
    durationSlots: durationToSlots(15),
    type: 'break',
    company: '',
    title: 'BREAK',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'fri-main-vise',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(16, 15),
    durationSlots: durationToSlots(25),
    type: 'solo',
    company: '',
    title: 'Vise',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'fri-main-closing',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(16, 45),
    durationSlots: durationToSlots(15),
    type: 'event',
    company: '',
    title: 'Brent Closing',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'fri-main-mariners',
    dayId: 'fri',
    venueId: 'main-stage',
    startSlot: timeToSlot(17, 0),
    durationSlots: durationToSlots(60),
    type: 'event',
    company: '',
    title: 'Mariners!',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },

  // ===== FRIDAY — LL-A Breakout =====
  {
    id: 'fri-lla-wealth',
    dayId: 'fri',
    venueId: 'll-a',
    startSlot: timeToSlot(11, 50),
    durationSlots: durationToSlots(20),
    type: 'panel',
    company: '',
    title: 'Wealth Panel (Shang)',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'fri-lla-pimco',
    dayId: 'fri',
    venueId: 'll-a',
    startSlot: timeToSlot(12, 20),
    durationSlots: durationToSlots(20),
    type: 'solo',
    company: '',
    title: 'PIMCO x2',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'fri-lla-open1',
    dayId: 'fri',
    venueId: 'll-a',
    startSlot: timeToSlot(12, 50),
    durationSlots: durationToSlots(20),
    type: 'open',
    company: '',
    title: 'OPEN',
    speakerIds: [],
    isSponsored: false,
    isTbd: true,
    notes: '',
  },
  {
    id: 'fri-lla-open2',
    dayId: 'fri',
    venueId: 'll-a',
    startSlot: timeToSlot(13, 30),
    durationSlots: durationToSlots(40),
    type: 'open',
    company: '',
    title: 'OPEN',
    speakerIds: [],
    isSponsored: false,
    isTbd: true,
    notes: '',
  },

  // ===== FRIDAY — LL-B Breakout =====
  {
    id: 'fri-llb-ppli',
    dayId: 'fri',
    venueId: 'll-b',
    startSlot: timeToSlot(11, 50),
    durationSlots: durationToSlots(20),
    type: 'solo',
    company: '',
    title: 'Jim + Golconda / PPLI',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'fri-llb-open1',
    dayId: 'fri',
    venueId: 'll-b',
    startSlot: timeToSlot(12, 20),
    durationSlots: durationToSlots(20),
    type: 'open',
    company: '',
    title: 'OPEN',
    speakerIds: [],
    isSponsored: false,
    isTbd: false,
    notes: '',
  },
  {
    id: 'fri-llb-open2',
    dayId: 'fri',
    venueId: 'll-b',
    startSlot: timeToSlot(12, 50),
    durationSlots: durationToSlots(20),
    type: 'open',
    company: '',
    title: 'OPEN',
    speakerIds: [],
    isSponsored: false,
    isTbd: true,
    notes: '',
  },
];

const SEED_CONTACTS: Contact[] = [];

export function createInitialState(): AppState {
  return {
    version: 1,
    days: SEED_DAYS,
    venues: SEED_VENUES,
    slots: SEED_SLOTS,
    contacts: SEED_CONTACTS,
    lastModified: new Date().toISOString(),
  };
}
